[project]
name = "etl-sdg-project"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.52",
]

[dependency-groups]
dev = [
    "graphviz>=0.21",
    "pytest>=9.1.1",
    "python-docx>=1.2.0",
]
